### ISSUE TITLE
Call to undefined method PayPay\OpenPaymentAPI\Models\CapturePaymentAuthPayload::setCodeType()

### ISSUE THREAD

**Issue by rndbjitgroup** [paypay/paypayopa-sdk-php#202]
**Describe the bug**
When execute capture payment, there is showing "Call to undefined method PayPay\OpenPaymentAPI\Models\CapturePaymentAuthPayload::setCodeType()". In the package Models\CapturePaymentAuthPayload method, there is no exist the method but if remove the line $CAPayload->setCodeType("ORDER_QR"); from the code, there is showing another error "PayPay\OpenPaymentAPI\Controller\ClientControllerException
Order not found | [OPABD667B96120A4632BA10A42B212C4C2E]".

**To Reproduce**
1. Go to  https://developer.paypay.ne.jp/products/docs/webpayment#capture-payment
2. Execute Capture Payment  
3. See error
Call to undefined method PayPay\OpenPaymentAPI\Models\CapturePaymentAuthPayload::setCodeType()
4. Since method is not exist the package for Models\CapturePaymentAuthPayload so remove the line $CAPayload->setCodeType("ORDER_QR"); 
5. There is showing another error 
PayPay\OpenPaymentAPI\Controller\ClientControllerException
Order not found | [OPABD667B96120A4632BA10A42B212C4C2E]".

Would you please resolve it.

**Comment by curtisfennerpaypay** [comment]
Hello

The code sample on the linked page appears to be incorrect.

There is no `codeType` parameter in the **[Capture a payment authorization](https://www.paypay.ne.jp/opa/doc/v1.0/preauth_capture#operation/capturePaymentAuth)** API, so it does not need to be set.

As a result, the `CapturePaymentAuthPayload` class does not have a `setCodeType` method, and there is no need to specify it.

------

The [Order not found](https://www.paypay.ne.jp/opa/doc/v1.0/preauth_capture#section/Response-code-list) error is returned by the capture-payment API when the `merchantPaymentId` field does not match any existing preauthorization.

Please ensure that the provided `merchantPaymentId` matches the `merchantPaymentId` from a successful invocation of the [create payment authorization API](https://www.paypay.ne.jp/opa/doc/v1.0/preauth_capture#operation/createAuth).
