### ISSUE TITLE
Please don't output help information with ClientControllerException.

### ISSUE THREAD

**Issue by jcong7495** [paypay/paypayopa-sdk-php#245]
Is it possible to prevent the [help information](https://github.com/paypay/paypayopa-sdk-php/blob/c8550ef15810ce30d5ece5b7b30caa2b0e41d258/src/core/ClientControllerException.php#L30) from being output with ClientControllerException?
This is because the header function cannot be used after throwing an exception.

**Comment by curtisfennerpaypay** [comment]
The unnecessary `print` has been removed in version `2.0.4`, which should be available from packagist shortly.
