### ISSUE TITLE
composer.lock is redundant for libraries

### ISSUE THREAD

**Issue by sanmai** [paypay/paypayopa-sdk-php#25]
This library includes `composer.lock` which is:

- Not used when installing any library with Composer. [It's just outright ignored.](https://getcomposer.org/doc/02-libraries.md#lock-file)
- It hinders testing under different versions of dependencies. Say, Travis CI would normally do `composer install` for you during CI, with `composer.lock` present you would have to do `composer update` additionally. Likewise, contributors would have to do that too.
- It pollutes `composer.json` update diffs, since they both have to be updated.

There's no point to keep it committed in a library, on the contrary with a deployable project, which this project is not.

[Here's what the documentation says](https://getcomposer.org/doc/02-libraries.md#lock-file):

> However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

**Comment by shreyanshp** [comment]
I believe having a lock file helps in long run and specially when we have multiple people working on same repo
As for the point of using old package/library version, I believe that gets solved by dependabot

I will close this for now, feel free to join the slack and let us know your thoughts!
